[workspace]
members = []
resolver = "2"

[workspace.package]
authors = ["Nikola R. Hristov <nikola@nikolahristov.tech>"]
documentation = "https://docs.land.playform.cloud/"
edition = "2021"
homepage = "https://land.playform.cloud/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/CodeEditorLand/Property"
