[workspace]
members = []
resolver = "2"

[workspace.package]
authors = ["Nikola R. Hristov <Nikola@Playform.Cloud>"]
documentation = "https://Docs.Land.Playform.Cloud/"
edition = "2021"
homepage = "https://Land.Playform.Cloud/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "HTTPS://GitHub.Com/CodeEditorLand/Foundation"
