[workspace]
resolver = "2"
members = ["Cargo/Maintain"]

[workspace.package]
authors = ["Nikola Hristov <nikola@nikolahristov.tech>"]
homepage = "https://land.playform.cloud/"
repository = "https://github.com/CodeEditorLand/Environment"
edition = "2021"
