packages:
    - "Land/**"
    - "!Land/**/build"
    - "!Land/**/dist"
    - "!Land/**/Target"
    - "!Land/**/target"

    - "NPM/**"
    - "!NPM/**/build"
    - "!NPM/**/dist"
    - "!NPM/**/Target"
    - "!NPM/**/target"
