name: Git

concurrency:
    group: Git-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.1
              with:
                  submodules: recursive

            - run: chmod a+x Script/Cache/Get.sh ; Script/Cache/Get.sh

            - run:
                  chmod a+x Script/Clone/Repository.sh ;
                  Script/Clone/Repository.sh

            - run:
                  chmod a+x Script/Configure/Repository.sh ;
                  Script/Configure/Repository.sh

            - run:
                  chmod a+x Script/Setting/Repository.sh ;
                  Script/Setting/Repository.sh
